
// The .proto file defines the service contract including request and response structures.

//    1. In REST, you’d say POST /stocks or DELETE /stocks/{id}.
//    2. In gRPC, you just define rpc AddStock and rpc DeleteStock.
//    3. The method name conveys the intent (add, delete, update, etc.).
//    4. The request/response messages carry the data.

//to compile and generate java classes run in intellij terminal using mvn of this project > mvnw.cmd clean package -DskipTests & to run spring-boot-application using project maven : > mvnw.cmd spring-boot:run -DskipTests

//    to compile and generate java classes run in intellij terminal using mvn of this project > mvnw.cmd clean package -DskipTests & to run spring-boot-application using project maven : > mvnw.cmd spring-boot:run -DskipTests

//    to run this file > sh request.sh
// package line is crucial. It means the fully qualified service name is: com.mylearning.stock_trading_server.StockTradingService
syntax = "proto3";

package com.mylearning.stock_trading_server;

option java_multiple_files=true;
// option java_package = "<your-package-name-goes-here>.proto";
option java_package="com.mylearning.grpc";
option java_outer_classname="StockTradingProto";

import "google/protobuf/timestamp.proto";

service StockTradingService {
  // UNARY - RPC -> get current stock price
  //rpc GetStockPrice (StockPriceRequest) returns (StockPriceResponse);
  rpc GetStockPrice (StockPriceRequest) returns (StockPriceResponse){}

  // "POST-like" method: add a new stock
  rpc AddStock (AddStockRequest) returns (AddStockResponse);

  // "DELETE-like" method: remove a stock by symbol
  rpc DeleteStock (DeleteStockRequest) returns (DeleteStockResponse);
}

message StockPriceRequest{
  string stock_name = 1;
}

message StockPriceResponse{
  string stock_name = 1;
  double price = 2;
  string currency = 3;
  google.protobuf.Timestamp timestamp = 4;
  string authenticationName = 5;
  string authenticationPrincipal = 6;
}

// Request/Response messages
message AddStockRequest {
  string stock_symbol = 1;
  double price = 2;
  string currency = 3;
}

message AddStockResponse {
  string status = 1; // e.g. "SUCCESS"
}

message DeleteStockRequest {
  string stock_symbol = 1;
}

message DeleteStockResponse {
  string status = 1; // e.g. "DELETED"
}

